import type { Metadata } from "next";
import { Geist, Geist_Mono, Sirin_Stencil, SUSE } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sirinStencil = Sirin_Stencil({
  variable: "--font-sirin-stencil",
  subsets: ["latin"],
  weight: "400",
});

const suse = SUSE({
  variable: "--font-suse",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const inter = {
  variable: "--font-inter",
  subsets: ["latin"],
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${suse.variable} ${sirinStencil.variable}  antialiased bg-secondary max-w-[1660px] mx-auto`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
